server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.16.3.30:3306/xretail?connectTimeout=5000&socketTimeout=20000
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver